### ISSUE TITLE
No me funciona el chat con Slackbot

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Slack#12]
Sale esto en consola y el chat aparece vacío:

![imagen](https://user-images.githubusercontent.com/1384919/38507520-0b1103b6-3c1d-11e8-84d1-f160eb2938fc.png)

![imagen](https://user-images.githubusercontent.com/1384919/38507531-115f1096-3c1d-11e8-8a45-be5dabc3b583.png)

**Comment by RJ64** [comment]
Corregido
