### ISSUE TITLE
Cuando abro la opción de "Todos los hilos" se lía en consola

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Slack#13]
Cuando hago click en "Todos los hilos" aparecen todos estos errores en consola:

![imagen](https://user-images.githubusercontent.com/1384919/38507628-56bd5756-3c1d-11e8-80de-f3cc24bfb0ab.png)

Ese error muchas veces seguido de estos:

![imagen](https://user-images.githubusercontent.com/1384919/38507661-67a9e87c-3c1d-11e8-835a-2d016c287ef2.png)

y luego otra vez muchas veces el primer error hasta llegar a este otra vez:

![imagen](https://user-images.githubusercontent.com/1384919/38507707-82d883ba-3c1d-11e8-9e23-fd7541f07443.png)

**Comment by RJ64** [comment]
Solucionado
