### ISSUE TITLE
Hay muchas diferencias visuales con el original

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Slack#2]
Aquí tienes la comparativa de la app de Slack para horbito y la app oficial:

- Sidebar

![image](https://user-images.githubusercontent.com/1384919/34416304-34269542-ebf3-11e7-83e3-562d4de1e84d.png)

- Main

![image](https://user-images.githubusercontent.com/1384919/34416358-68a0d814-ebf3-11e7-925c-75025c057eb2.png)

**Comment by RJ64** [comment]
Ya se parece más
