### ISSUE TITLE
Se debe poder añadir varios workplaces y poder cambiar cómodamente entre ellos

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Slack#3]
Pues eso

**Comment by RJ64** [comment]
Ya está. Solo falta detectar cuando recibo el permiso. Estoy mirándolo con Nacho

**Comment by jorge9200** [comment]
que te falta?

**Comment by RJ64** [comment]
Funciona bien pero cuando el usuario añade un workplace no lo detecto. Habría que cerrar y abrir el programa de Slack. A donde quiero llegar es que para cerrar esta issue hay que hacer funcionar la función: api.integration.slack.on( 'added-account', function( payload ) { para que detecte cuando añada un nuevo workplace y se lo ponga

**Comment by jorge9200** [comment]
no funciona el evento de added-account? debería funcionar!

**Comment by jorge9200** [comment]
echale un ojo y si te falla me dices

**Comment by RJ64** [comment]
Ok. Funciona.
