### ISSUE TITLE
Desarrollos pendientes

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Slack#4]
Estos son los desarrollos pendientes:

- Poder cambiar tu status
- Poder iniciar sesión en varios workspaces y poder cambiar entre ellos

![image](https://user-images.githubusercontent.com/1384919/34488619-789f1912-efd9-11e7-832a-2908d0f72153.png)

- Poder hacer snooze

![image](https://user-images.githubusercontent.com/1384919/34489298-15851d10-efdc-11e7-81fa-2a5a0f99d35e.png)

- Soportar threads

![image](https://user-images.githubusercontent.com/1384919/34488694-be2b3664-efd9-11e7-95b6-f34cfff553fd.png)

![image](https://user-images.githubusercontent.com/1384919/34488888-771552ea-efda-11e7-8caa-7de44b659f52.png)

![image](https://user-images.githubusercontent.com/1384919/34488720-d66f3e3c-efd9-11e7-9d2b-aa675fb7d95c.png)

- Poder editar y borrar un mensaje

![image](https://user-images.githubusercontent.com/1384919/34488996-f006920e-efda-11e7-8370-c29f24f55b1b.png)

- Negrita en canales con mensajes nuevos

![image](https://user-images.githubusercontent.com/1384919/34489169-7a1a6600-efdb-11e7-8f5b-6e0330ce9147.png)

- Negrita y badge cuando tienes mensajes directos sin leer

![image](https://user-images.githubusercontent.com/1384919/34489185-949e1bac-efdb-11e7-8a98-b107c3e99b34.png)

- Lucecita o badge en el icono de la app de Slack cuando hay novedades

![image](https://user-images.githubusercontent.com/1384919/34489221-c0c4f516-efdb-11e7-8bbc-3ddbc0384fc0.png)

- Popup cuando recibes mensajes directos

![image](https://user-images.githubusercontent.com/1384919/34489326-363c5852-efdc-11e7-8fee-8399fd2be1c7.png)

- Cargar los nuevos mensajes recibidos en tiempo real (tanto en los canales o en los mensajes directos)

En principio eso es todo, a lo mejor sale algo más a medida que avancemos pero esto es lo que se me ocurre por ahora

**Comment by RJ64** [comment]
No funciona correctamente la función mpimHistory. No devuelve los mensajes directos de grupo sin leer. No sé si es un problema de vuestra implementación o de slack pero para todos los demás (mensajes directos, canales, canales privados... cada uno tiene su función) funciona bien

**Comment by RJ64** [comment]
Actualización:

 - Los status están compuestos por un mensaje y un emoji. No hay ningún método ni forma para mapear el emoji con su imagen. He creado un issue a ver si se encuentra una solución. Lo que decidáis, se hace.
 - Se pueden añadir múltiples workspaces, cambiar entre ellos y desloguearse.
 - El set yourself away entiendo que sirve para que los demás vean si estás conectado o no. A través de la API no encuentro forma de activarlo. Solo funciona a través de su web.

 - Hay problemas con la api de recuperar hilos. Se ha abierto un issue
 - En los canales se ve si un mensaje tiene hilos, y si haces click se abre el lateral pero son en canales, no en grupos, conversaciones privadas... Misma issue que antes.

 - Se pueden editar y eliminar mensajes

- Negritas y badges funcionando correctamente salvo en mensajes privados con múltiples usuarios. Issue creada

 - No recibimos el evento cuando se producen cambios o nos escriben con lo que snooze funciona pero de momento no hay nada que notificar. 

Pendiente:

- [ ] Status

- [x] Threads

- [ ] Nuevos 

- [x] Adjuntar archivo desde horbito

**Comment by jorge9200** [comment]
Quédatela tu y vete actualizando con los estados, cuando termines nos la devuelves!
