### ISSUE TITLE
Implementar el evento added-account

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Slack#5]
Igual que en Outlook, recibes el evento en cuanto el proceso OAuth se ha completado con éxito.

**Comment by RJ64** [comment]
No recibo nada con esto:

api.integration.slack.on( 'added-account', function( payload ) {

A ver si soy yo o eres tú

**Comment by RJ64** [comment]
Da este error: TypeError: api.integration.slack.on is not a function

**Comment by icastillejogomez** [comment]
El evento esta llegando a front. Puede quedar la parte del control trigger. Esto ya es cosa de @jorge9200

**Comment by jorge9200** [comment]
vale ya esta funcinando:

![image](https://user-images.githubusercontent.com/8724844/37287075-2b3dd90e-2604-11e8-942b-56be6ee8d777.png)

Ten en cuenta que la información que da el evento no tiene utilidad, simplemente saber que la autorizacion se ha completado correctamente.

Ahora solo falta tratar la respuesta:
-> Si auth bien, paso al siguiente paso
-> Si auth mal, tiro un alert con el error que me devuelva

**Comment by RJ64** [comment]
En principio ya está funcionando. Probadlo. Una cosa, la ventana que se abra para aceptar los permisos se queda abierta con un Success, fyi

**Comment by jorge9200** [comment]
no se a que puede ser debido, @icastillejogomez @javiergarmon ?
