### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by RJ64** [Inevio/Slack#6]
No tengo ninguna forma de mapear los emoji. En slack los emojis son una gigante imagen (un sprite) y lo va moviendo según el emoji. Pero no sé qué posición le ocupa a cada emoji

**Comment by jorge9200** [comment]
y que necesitas de aqui? el sprite?

**Comment by RJ64** [comment]
No, el sprite le puedo coger. El problema es que Slack me dice que el usuario X tiene el estado algo con el icono ':gafas_de_sol:', pero yo no tengo forma de saber a qué imagen le corresponde ese icono. Salvo que sea un icono creado por la persona (no de los estándares de Slack) que me dan también la imagen, los iconos de Slack se encuentran en un sprite y no tengo forma de saber cuál es para colocar el sprite en la posición correcta y que se muestre el icono del estado del usuario.

**Comment by jorge9200** [comment]
mmmm intenta probar con un modulo de este tipo:

https://github.com/iamcal/js-emoji

puede que alguno no lo detecte pero es lo que hay

**Comment by icastillejogomez** [comment]
Este articulo de StackOverFlow quizas te ayude. No veo la forma de hacerlo sino...

**Comment by icastillejogomez** [comment]
Si aun asi no lo soluciona y crees que hay otra solución dímelo y la implemento.

**Comment by icastillejogomez** [comment]
Escribo aquí para que quede constancia del estado de esta issue:

Ya encontré la forma de hacer emojis con JS y compatibles con el navegador y se lo comente a Jorge y Jorge a Ricardo vía Telegram por lo que supongo que el siguiente estado de esta issue será que Ricardo nos comente algún problema o ya lo haya implementado. 

 Fantastic!

**Comment by icastillejogomez** [comment]
https://www.webpagefx.com/tools/emoji-cheat-sheet/

Comprueba si esta lista concuerda con al de slack. @RJ64

**Comment by jorge9200** [comment]
Los emojis siguen sin funcionar, hay que hacerlos funcionar
