### ISSUE TITLE
Función mpimHistory - Mensajes sin leer

### ISSUE THREAD

**Issue by RJ64** [Inevio/Slack#7]
No funciona correctamente la función mpimHistory. No devuelve los mensajes directos de grupo sin leer. No sé si es un problema de vuestra implementación o de slack pero para todos los demás (mensajes directos, canales, canales privados... cada uno tiene su función) funciona bien

**Comment by icastillejogomez** [comment]
La función es un bindeo completo a la API de Slack. Te dejo el link de la documentación de ese método en concreto para que me digas si funciona según lo esperado en la documentación o claramente hay un fallo por nuestra parte o por la de Slack. 

https://api.slack.com/methods/mpim.history

**Comment by RJ64** [comment]
Parece que ya funciona. No sé qué pasaba
