### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by RJ64** [Inevio/Slack#8]
Las funciones imReplies, mpimReplies y groupsReplies (básicamente las de recuperar threads en todos los lados salvo en channels) dan el error SERVER UNAVAILABLE.

También comentar que no hay ningún método para recuperar threads. Hay que llamar primero a channelsList, imList, mpimList, groupsList para recuperar todos los canales, grupos..., luego recuperar todos los mensajes de cada uno de los canales, grupos..., navegar por todos los mensajes buscando los hilos y ya una vez recuperados todos los hilos llamar a channelsReplies, imReplies, mpimReplies o groupsReplies para recuperar todo el hilo

**Comment by icastillejogomez** [comment]
> Las funciones imReplies, mpimReplies y groupsReplies (básicamente las de recuperar threads en todos los lados salvo en channels) dan el error SERVER UNAVAILABLE.

Esto claramente es un error por nuestra parte. Lo estoy mirando ahora mismo. En nada te diré algo.

> También comentar que no hay ningún método para recuperar threads. Hay que llamar primero a channelsList, imList, mpimList, groupsList para recuperar todos los canales, grupos..., luego recuperar todos los mensajes de cada uno de los canales, grupos..., navegar por todos los mensajes buscando los hilos y ya una vez recuperados todos los hilos llamar a channelsReplies, imReplies, mpimReplies o groupsReplies para recuperar todo el hilo

Nosotros no hemos investigado al respecto del flujo, supongo que habrás investigado y pensado al respecto pero si crees que es la única forma de hacerlo poco más podemos hacer, es una pena. :(

Si por nuestra parte podemos hacer algo para no hacer tantas llamadas dímelo y lo implemento.

**Comment by icastillejogomez** [comment]
Necesito saber en que caso te da ese error para poder reproducirlo. ¿Me puedes decir que tengo que hacer en la app de horbito para que lleguen a back esas peticiones.?

**Comment by RJ64** [comment]
Para reproducirlo cread un hilo en un grupo privado, en un canal privado y en una conversación entre dos, luego entrad en horbito a esas conversaciones y haced click en el hilo para abrirlo. Tras unos segundos da un error de SERVER UNAVAILABLE. Solo funciona al abrir un hilo en un canal.

**Comment by icastillejogomez** [comment]
Dejo aquí lo que nos escribiste por el grupo de Telegram para:

> Vale, no cosigo dejaroslo fácil para reproducir el error. Meramente probad a crear un hilo en una conversación con alguien y probad

**Comment by icastillejogomez** [comment]
Puedes probar si sigue fallando?

**Comment by icastillejogomez** [comment]
Creo que ya funciona

**Comment by RJ64** [comment]
Sí, ya funciono y lo dejé listo
