### ISSUE TITLE
Attach File

### ISSUE THREAD

**Issue by RJ64** [Inevio/Slack#9]
No hay función para adjuntar archivo de horbito

**Comment by icastillejogomez** [comment]
Ya he añadido esta funcionalidad. El interfaz del método se puede ver en la imagen adjunta. 

![image](https://user-images.githubusercontent.com/16567802/37280098-1a42e958-25ed-11e8-80b6-29b664a3a34a.png)

Solo falta que @jorge9200 despliegue front de nuevo para que este la función disponible.

**Comment by jorge9200** [comment]
subido, ya deberia estar disponible

**Comment by RJ64** [comment]
Dos cosas. A la función filesUploadFromHorbito le falataría en los parámetros filename y initial_comment no? Y me sigue sin funcionar. No me devuelve nada. Probad ahora a subir un archivo en Slack en Horbito

**Comment by icastillejogomez** [comment]
El filename lo extraigo del nombre del fichero, el initial_comment deberias ver con que clave se pasa dentro de params y pasarlo, debería funcionar.

**Comment by icastillejogomez** [comment]
Vale por lo que veo ya funciona, pero deberías cambiar "channel" por "channels" como ves en la docu es una lista (string) de canales separados por comas. Al cambiar eso y añadir la descripción inicial ya debería funcionarte todo.

**Comment by icastillejogomez** [comment]
Aun asi, fsNodeIds puede ser un array de nodos o un solo nodo, por si te viene bien saberlo. Pero el params seria común a todos. Si lo ves necesario podemos adaptar el método para que recibar varios fsNodeIds con su params particular cada uno. Tu me dices.

**Comment by icastillejogomez** [comment]
Nos comenta Ricardo por Telegram que sigue fallando, me la asigno para ver que pasa.

**Comment by icastillejogomez** [comment]
Ya funciona. 

De todas formas me lo muestra como si lo hubieras subido tu no?

![image](https://user-images.githubusercontent.com/16567802/37698272-3b7d9c5c-2ce2-11e8-9fa8-0d732ca178c1.png)
